require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/mongoid-suicide.rb'
